name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        type: boolean
        description: 'Run Specific Job'
        required: false
      custom_messages:
        type: string
        description: 'Enter a custom'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"

  job2:
    runs-on: ubuntu-latest
    name: 'Printing Custom Message'
    steps:
      - run: echo ${{ inputs.custom_messages}}
